### ISSUE TITLE
[Bug]: Crash with Aquaculture 2

### ISSUE THREAD

**Issue by Peach774** [samedifferent/Ecologics#1]
### Mod Version

1.1.0

### Mod Loader

Forge

### Mod Loader Version

39.0.45

### What happened?

The game crashes with Aquaculture 2. Disabling Ecologics allows the mod to load successfully.

### latest.log

https://gist.github.com/Peach774/0e3fc40da35dd96ae05043c9081b785d

**Comment by samedifferent** [comment]
Try the latest version

**Comment by Peach774** [comment]
The newest version fixes this, thank you
