### ISSUE TITLE
[Bug]: Incompatibility with Earth2Java

### ISSUE THREAD

**Issue by Ch4mp10** [samedifferent/Ecologics#100]
### Mod Version

2.1.10

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### What happened?

When I installed E2J 1.9.3 squirrels stopped spawning. It works fine with Chirpy's Wildlife.

### latest.log

[2022-11-27-7.log.gz](https://github.com/samedifferent/Ecologics/files/10099133/2022-11-27-7.log.gz)

**Comment by samedifferent** [comment]
Increase the spawn weight of squirrels in the mod config.
