### ISSUE TITLE
[Bug]: penguins

### ISSUE THREAD

**Issue by sgage13** [samedifferent/Ecologics#102]
### Mod Version

1.19.2

### Mod Loader

Fabric

### Mod Loader Version

2.1.11

### What happened?

when rendering a penguin crashes the game

### latest.log

[crash-2022-12-14_17.22.45-client.txt](https://github.com/samedifferent/Ecologics/files/10232666/crash-2022-12-14_17.22.45-client.txt)

**Comment by samedifferent** [comment]
Issue is with Faster Entity Animations
