### ISSUE TITLE
[Bug]: snow spawns on thin ice, revealing it

### ISSUE THREAD

**Issue by Crows-Parliament** [samedifferent/Ecologics#107]
### Mod Version

2.1.11

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### What happened?

As in title, it makes it too easy to find, as it gets covered, unlike normal ice

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/10530632/latest.log)

**Comment by samedifferent** [comment]
I fixed this in the 1.19.3 and 1.18.2 versions, 1.19.2 is no longer supported
