### ISSUE TITLE
walnut boats unbreakable and crash server once set on fire

### ISSUE THREAD

**Issue by macarango** [samedifferent/Ecologics#109]
### Mod Version

1.19.3

### Mod Loader

Fabric

### Mod Loader Version

1.19.3

### What happened?

i made a walnut boat to travel back home but once i tried to break it it just started turning even after i hit about 50 times after eachother eventualy i tried to set it on fire but it crashed my server i saw a comment saying that coconut boats were also unbreakable so im assuming this can also happen to the other custom wood boats

### latest.log

i dont have a file sorry

**Comment by SkyArrow76** [comment]
I've encountered this as well with coconut boats. But not on fire, just when placing them down at all, insta-crashed

**Comment by maplehashbrown** [comment]
same with azalea boats, I set it on fire now I can't log into my world without it crashing. it's solo world

**Comment by gabriel-andreescu** [comment]
[crash-2023-03-05_15.51.07-server.txt](https://github.com/samedifferent/Ecologics/files/10891947/crash-2023-03-05_15.51.07-server.txt)
