### ISSUE TITLE
[Bug]: Configs for Coconut Trees

### ISSUE THREAD

**Issue by WenXin20** [samedifferent/Ecologics#12]
### Mod Version

v1.2.1

### Mod Loader

Forge

### Mod Loader Version

v39.0.88

### What happened?

In my opinion, there are too many coconut trees generating on beaches. Perhaps a config option can be added to change the generation rate of palm trees.

### latest.log

--

**Comment by UdoMorgenstern** [comment]
adjacent problem arises with the Coconut Slices and Crabs - I planted some coconut trees (as in 40+) and there are a lot of crabs now, could get out of hands quickly. 
![image](https://user-images.githubusercontent.com/90903255/156632970-9b63d1cf-35c9-4452-92f4-52b9dd8b0a99.png)

**Comment by samedifferent** [comment]
Configs have been added in the latest update

**Comment by WenXin20** [comment]
Thanks!
