### ISSUE TITLE
[Bug]: FABRIC 1.18.2 version not naturally generating content

### ISSUE THREAD

**Issue by Heamaci** [samedifferent/Ecologics#17]
### Mod Version

1.4.0

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

![imagen](https://user-images.githubusercontent.com/67716228/161397922-4561bc22-7630-4b88-ab9c-47f0916ab44a.png)
I've removed basically every content mod and this is all thats left in my mod folder. It seems that the fabric version doesn't naturally generate any of the features mentioned except walnut trees. I haven't found a single mob or feature that isn't a walnut tree without using creative. 

### latest.log

There isn't any crashes

**Comment by samedifferent** [comment]
Please provide your latest.log file

**Comment by Heamaci** [comment]
[latest.log](https://github.com/samedifferent/Ecologics/files/8405287/latest.log)

**Comment by PhoenixVX** [comment]
Can you attempt `/locatebiome minecraft:beach`, tp to that beach, then on that beach, type `/placefeature ecologics:coconut`?

This should place a tree.

**Comment by Heamaci** [comment]
> Can you attempt `/locatebiome minecraft:beach`, tp to that beach, then on that beach, type `/placefeature ecologics:coconut`?
> 
> This should place a tree.

Yes, this works

**Comment by PhoenixVX** [comment]
Okay, create a new world, note the seed down, go to a beach and find if or if not there are any coconut trees. Relay that information back here.

**Comment by Heamaci** [comment]
SEED: -5427182365627808776
All i did was /locatebiome the nearest beach and there is just huge empty spaces with no trees at all

**Comment by Heamaci** [comment]
I found it! Kotlin 1.6.10 is somehow preventing the trees from spawning

**Comment by PhoenixVX** [comment]
Huh...??? Kotlin is a programming language. fabric-language-kotlin shouldn't have anything to do with that. The more likely option would be that a mod which uses Kotlin and modifies biomes is messing up the weighting.

**Comment by Heamaci** [comment]
> Huh...??? Kotlin is a programming language. fabric-language-kotlin shouldn't have anything to do with that. The more likely option would be that a mod which uses Kotlin and modifies biomes is messing up the weighting.

I removed it, made a new world, same seed, and the trees were there. I wanted to make sure, so i added it back in, made a new world with the same seed and the trees were gone.

**Comment by PhoenixVX** [comment]
Of the mods listed above in the picture, I have not noticed any that use Kotlin, so it's hard to tell which mod might actually be causing this issue.

**Comment by Hueitor** [comment]
hey, here too, i did the same as the OP, could only place coconut tree, desert monument and walnut tree, the others give back an error. I'm not using Kotlin, and I'm using terralith along with this mod, does it have any incompability?

**Comment by PhoenixVX** [comment]
Are you attempting 1.4.0 content or 1.5.0 content? If it's Fabric, then you must test 1.4 content as 1.5 hasn't been ported as of yet.
As for the other question, it _shouldn't_ have an incompatibility, but Minecraft can produce very unexpected results in certain cases.

**Comment by Hueitor** [comment]
1.4 content, the fabric version of 1.5 wasnt up for download on curseforge when i downloaded it.
(i'm on fabric)

**Comment by PhoenixVX** [comment]
Hmm... could you provide a log? A log will contain the full set of mods, so while terralith may or may not be causing it, we will be able to identify a potential problem in totality.

**Comment by Hueitor** [comment]
i just created another world with the same mod list and some shells and coconut trees spawned, i didnt change a thing between this world and the last. Could it be that something is bugging the generation with the first created world? 

![image](https://user-images.githubusercontent.com/93229227/161879428-66c0af0e-d40b-4c41-acc6-b54ae443e661.png)

**Comment by PhoenixVX** [comment]
Did you generate the previous world without the mod AND did you go to a chunk you previously visited/generated?

**Comment by Hueitor** [comment]
nope, both worlds were generated on a fresh MultiMC instance, i'm building a modpack for my next playtrough, and those are my first 2 worlds generated on the instance.

here's the log file:
https://paste.ee/p/fGCkf

**Comment by PhoenixVX** [comment]
![image](https://user-images.githubusercontent.com/24632178/161880129-52a225a7-d34b-422b-9b90-9b835f883992.png)
uhh...?

**Comment by Hueitor** [comment]
![image](https://user-images.githubusercontent.com/93229227/161880124-1dfd4a13-c79f-4780-ac57-46f204d7a925.png)

this is my mod list at the moment

**Comment by Hueitor** [comment]
welp, idk about that entity_gravity stuff, maybe some forge mod i downloaded by accident, let me check

**Comment by PhoenixVX** [comment]
Forge mods wouldn't be loaded, rather one of those Fabric mods have invalid JSONs, likely the Architectury ones as oversights between codebases.

**Comment by Hueitor** [comment]
hmmm idk, i'll have a look to see wich mod is causing that. But now your mod is working greatly, just found more coconut trees in fresh chunks, thanks for your time dude!

**Comment by PhoenixVX** [comment]
No problem. Have a great time with Ecologics!

**Comment by Alec153** [comment]
I had mentioned it in the discord a week ago but I am also having the same issue on fabric. I have an extensive mod list including kotlin so i probably just need to test some more.

**Comment by PhoenixVX** [comment]
Can you first please try the same seed without any other mods other than the absolute necessary, E.g. Fabric API, Ecologics, and Geckolib?

**Comment by samedifferent** [comment]
I believe this is in relation to #23, which I fixed here: https://github.com/samedifferent/Ecologics/commit/d574d0331c5cb7ce5a2b2a93419154ffdc2f7247
