### ISSUE TITLE
[Bug]: Thin Ice has a lattice/grid-like appearance

### ISSUE THREAD

**Issue by Helpbot3000** [samedifferent/Ecologics#18]
### Mod Version

1.5.1

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.2-40.0.36

### What happened?

Unlike regular ice and glass, the sides of thin ice blocks are visible through other thin ice blocks placed next to them, giving patches of thin ice a grid-like appearance.

### latest.log

I know this is a required section, but I don't think it'll be much help in this case.

**Comment by cowsha** [comment]
![изображение](https://user-images.githubusercontent.com/35926994/163307710-8d327985-ee04-4df9-8c46-96646deaf786.png)
Same here, it looks a bit better with Sodium, but grid still appears on chunk borders

**Comment by samedifferent** [comment]
This doesn't occur when the mod is played with on its own. It is usually caused by performance mods like Rubidium.

**Comment by Helpbot3000** [comment]
> This doesn't occur when the mod is played with on its own. It is usually caused by performance mods like Rubidium.

You say this, but I was using it 100% on its own.
