### ISSUE TITLE
[Bug]: Cannot Strip Various Logs/Wood

### ISSUE THREAD

**Issue by Healex2** [samedifferent/Ecologics#19]
### Mod Version

ecologics-FORGE-1.18.1-1.2.1.jar

### Mod Loader

Forge

### Mod Loader Version

39.1.0

### What happened?

Expected behavior: Be able to strip coconut logs (or wood) by right clicking them with any axe.
What happens: The coconut logs (or wood) remain in their original, non-stripped state. 

EDIT: Also tested in 1.18.2-1.5.1 version. Coconut (and Azalea) logs/wood strip correctly here, but Walnut logs/wood do not.

Tested with only Ecologics (& GeckoLib) in 1.18.1.

(Also checked the stripped versions exist via creative mode.)

Also tested in combination with other mods, including Create. 
I suspect this missing behavior also lets Create Saws not strip the coconut logs (or wood) either. 

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8405161/latest.log)

**Comment by samedifferent** [comment]
You are using a very outdated version. This bug has been long fixed.
