### ISSUE TITLE
[Bug]: Stripped Walnut Log & Wood

### ISSUE THREAD

**Issue by Healex2** [samedifferent/Ecologics#20]
### Mod Version

ecologics-FORGE-1.18.2-1.5.1

### Mod Loader

Forge

### Mod Loader Version

40.0.36

### What happened?

In the current version of Ecologics (at time of writing), the player is unable to strip Walnut Logs (and Walnut wood) by right clicking said block with an axe. 

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8405579/latest.log)

**Comment by samedifferent** [comment]
Fixed in latest version
