### ISSUE TITLE
[Bug]: Fabric version not generating content when world first loads, crashes on third and subsequent loads

### ISSUE THREAD

**Issue by CZX123** [samedifferent/Ecologics#25]
### Mod Version

1.5.1

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

[Issue 17](https://github.com/samedifferent/Ecologics/issues/17) is still happening in the latest Fabric version, but I have found how to reproduce it consistently, and how it sometimes does not happen, and also discovered a crash bug, so I think this warrants a new issue instead of reopening issue 17.

### Steps to Reproduce

- Launch Minecraft
- Open any world, or create a new one
- Fly around the world and try to find the new features

Only walnut trees generate, with no other features and no mob spawns, not even squirrels, as described in issue 17.
This line appears in the log file when loading the world:
`Applied 2 biome modifications to 2 of 61 new biomes in 6.200 ms`

- Now, Save and quit the world, and open up any world (can be the same one, or a newly created world)

This time, it appears that everything works fine, with all the features present, and mobs like squirrels, crabs and penguins spawning.
The relevant line now changes to this when loading the world:
`Applied 12 biome modifications to 6 of 61 new biomes in 1.988 ms`

- Save and quit again, and open up any world.

The relevant line now changes to this:
`Applied 22 biome modifications to 6 of 61 new biomes in 1.249 ms`

The game will crash with an exception when generating new chunks:
`Caused by: java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:frozen_river]=net.minecraft.class_1959@188e2633}]`

If you have the Not Enough Crashes mod installed, and tried creating more worlds, it will always crash with the same message.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8450599/latest.log)

**Comment by PhoenixVX** [comment]
Oooh... I'll need to take a look into this. Thanks for the comprehensive report!

**Comment by PhoenixVX** [comment]
Issue confirmed. This is starting to sound like a Fabric API bug. I'll need to get someone else to look over my biome modifications in the Fabric server.

**Comment by PhoenixVX** [comment]
Should be fixed in #[03fc56a](https://github.com/samedifferent/Ecologics/commit/03fc56a551492cd2cef03ac94367a8f6c39445b7). 

Details:
Re-adding biome modifications on server start instead of on mod start.

Ecologics Fabric 1.5.2 should be releasing soon on CurseForge.
Thanks for reporting and have a nice day!

**Comment by CZX123** [comment]
Nice, thanks for solving this real fast!
