### ISSUE TITLE
[Bug]: Biome Makeover - Ecologics incompatibilty involving signs

### ISSUE THREAD

**Issue by FnigePython** [samedifferent/Ecologics#26]
### Mod Version

1.5.2 - 1.18.2

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

Having Ecologics (Gecko + Cloth Config) and Biome Makeover (Archi + FrAPI) crashes the game when you place down one of ecologic's signs

### latest.log

[crash-2022-04-11_10.23.17-client.txt](https://github.com/samedifferent/Ecologics/files/8460261/crash-2022-04-11_10.23.17-client.txt)

**Comment by PhoenixVX** [comment]
Hmm, according to the log, this is the conflicting line and that spriteIdentifier is null. 
<https://github.com/samedifferent/Ecologics/blob/fabric/src/main/java/samebutdifferent/ecologics/client/renderer/block/ModSignBlockEntityRenderer.java#L67>

Interesting, considering this is just the sign block entity renderer copied. I'll have to check out if 1.18.2 does anything funky, or if it's just that mod combination causing such a situation.

**Comment by samedifferent** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3765328
