### ISSUE TITLE
[Bug]: Uncraftable Boats

### ISSUE THREAD

**Issue by Healex2** [samedifferent/Ecologics#28]
### Mod Version

ecologics-FORGE-1.18.2-1.5.5.jar

### Mod Loader

Forge

### Mod Loader Version

Forge 40.0.48

### What happened?

Expected to be able to make coconut/walnut/azalea/flowering azalea boats. 

### latest.log

Seriously you don't need the latest.log for this. Why is this required?
[latest.log](https://github.com/samedifferent/Ecologics/files/8485462/latest.log)

**Comment by samedifferent** [comment]
I fixed this in https://github.com/samedifferent/Ecologics/commit/364775903c3d63f38adfcfe75d4ead2c150921d6

This will be included in the next update :)

**Comment by samedifferent** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3764138
