### ISSUE TITLE
[Bug]: Enchantable Crab Claws

### ISSUE THREAD

**Issue by Healex2** [samedifferent/Ecologics#29]
### Mod Version

ecologics-FORGE-1.18.2-1.5.5.jar

### Mod Loader

Forge

### Mod Loader Version

40.0.48

### What happened?

Crab Claws can be enchanted with Mending, Unbreaking, Efficiency, and Curse of Vanishing. 
I assume this is not intended. 

### latest.log
(Removed log by Zero as it contained nothing of relevance)

**Comment by samedifferent** [comment]
This isn't a bug. The crab claws are just a less durable version of shears, so they can have any enchantment that shears can have. I don't really see a problem with this because other animal parts in Vanilla can be enchanted, like turtle shells.

**Comment by Healex2** [comment]
Ah, my misunderstanding then. Thanks ^L^
