### ISSUE TITLE
[Bug]: Weird Compat issue where chunk borders seen through ice with mod rubidium

### ISSUE THREAD

**Issue by WelpSTudent** [samedifferent/Ecologics#31]
### Mod Version

1.5.5

### Mod Loader

Forge

### Mod Loader Version

40.0.52

### What happened?

Weird Compat issue where chunk borders seen through ice with mod rubidium

Normal: 
![image](https://user-images.githubusercontent.com/63996164/163702569-63fdb34c-aa7a-4a7a-9a3c-39b4508aa800.png)
Bugged:
![image](https://user-images.githubusercontent.com/63996164/163702589-ec61c21d-31c3-4daf-bbc0-13902c378762.png)

### latest.log

nothing

**Comment by samedifferent** [comment]
This is an issue with Rubidium and does not occur with Ecologics on its own. Please submit this issue to Rubidium.
