### ISSUE TITLE
[Bug]: server crash

### ISSUE THREAD

**Issue by kuba26038** [samedifferent/Ecologics#32]
### Mod Version

ecologics-FORGE-1.18.2-1.6.0

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

my server crashes while booting up. i tried with and without the rest of my mods, the first log is with, the second without.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8546868/latest.log)

[latest.log](https://github.com/samedifferent/Ecologics/files/8546870/latest.log)

**Comment by PhoenixVX** [comment]
Caused by: java.lang.NoSuchMethodError: 'void samebutdifferent.ecologics.compat.quark.QuarkCompatClient.registerRenderLayers(net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent)'

@samedifferent This needs to be conditional, depending on if Quark is loaded.

**Comment by samedifferent** [comment]
It is conditional: https://github.com/samedifferent/Ecologics/blob/4e8680b8ab502876a6f653dd00e025e0b688b892/src/main/java/samebutdifferent/ecologics/compat/ModCompat.java#L36
That's strange.

**Comment by Freudeheit** [comment]
hope this is fixed soon this mod looks so nice :(

**Comment by samedifferent** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3765418

**Comment by spoorn** [comment]
Still happening for me using Ecologics 1.5.3
