### ISSUE TITLE
[Bug]: flowering_azalea_log and flowering_azalea_wood is missing minecraft:log block tag

### ISSUE THREAD

**Issue by Synthestra** [samedifferent/Ecologics#38]
### Mod Version

1.6.1

### Mod Loader

Forge

### Mod Loader Version

40.0.54

### What happened?

Flowering Azalea logs and wood blocks are missing minecraft:log tags, making leaves not recognise these blocks as valid log blocks.

### latest.log

n/a

**Comment by samedifferent** [comment]
Fixed in https://github.com/samedifferent/Ecologics/commit/a66f3f50d0ccb326c4606ccccd08bb1f367ac4a2
Download: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3767359
