### ISSUE TITLE
[Bug]: Could not parse loot table

### ISSUE THREAD

**Issue by Preciel** [samedifferent/Ecologics#39]
### Mod Version

1.6.2

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

Version 1.6.2 trigger error when trying to load recipes

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8550562/latest.log)

**Comment by Preciel** [comment]
Update: Error still occur in version 1.6.3

**Comment by brdle** [comment]
Issue with block registration that does not affect gameplay. A solution is currently in the works.
Fixed for Farmer's Delight blocks with #49

**Comment by samedifferent** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3790802
