### ISSUE TITLE
[Bug]: Access Widener causes crash with Physics Mod

### ISSUE THREAD

**Issue by haubna** [samedifferent/Ecologics#40]
### Mod Version

1.5.4

### Mod Loader

Fabric

### Mod Loader Version

0.13.3-1.18.2

### What happened?

This access widener causes an issue with the Physics Mod. It currently isn't used anywhere in the Ecologics Mod.

`accessible method net/minecraft/client/render/entity/MobEntityRenderer renderLeashPiece (Lnet/minecraft/client/render/VertexConsumer;Lnet/minecraft/util/math/Matrix4f;FFFIIIIFFFFIZ)V
`

### latest.log

https://pastebin.com/sxJpxu6i

**Comment by samedifferent** [comment]
Fixed in latest version
