### ISSUE TITLE
[Bug]: Missing other language localization

### ISSUE THREAD

**Issue by Zano1999** [samedifferent/Ecologics#44]
### Mod Version

1.6.2

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

Your mod dysplay names only in english (en_us.json) even with localization file of a supported language (it_it.json), I tried to rename it_it.json to en_us.json to force load that localization file, but in game instead of the translated text strings i see texts like "block.ecologics.azalea_planks"

### latest.log

https://gist.github.com/Zano1999/7aea657e97ac3e6c798e8ef41c792e13

**Comment by samedifferent** [comment]
This isn't my fault, the Italian translator just did an incomplete translation. If you are bilingual and would like to finish the translation yourself, you are welcome to submit a pull request :)

**Comment by Zano1999** [comment]
I can do this, but I've never figured out how to create a pull request
