### ISSUE TITLE
[Bug]: Incompatibility with Rubidium

### ISSUE THREAD

**Issue by alexstanleeee** [samedifferent/Ecologics#45]
### Mod Version

1.6.2

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

Using the mod in conjunction with Rubidium results in a strange bug where thin ice reveals chunk borders. I did in fact check this with F3 and G, revealing these were in fact the borders of chunks.
![image](https://user-images.githubusercontent.com/104217120/166214590-f487372c-7172-47c6-b87e-680dcef5825d.png)

### latest.log

![image](https://user-images.githubusercontent.com/104217120/166214838-d0775794-5e6b-4ecb-bf5b-9ff961066b5b.png)

**Comment by samedifferent** [comment]
This is rubidium's fault. I am setting the blocks transparency in the correct way. I don't understand the funky stuff that Rubidium does to achieve better performance. Please submit an issue to them.
