### ISSUE TITLE
[Bug]: Azalea Flowers use Azalea Log even if config "Replace Azalea Tree" is set to off.

### ISSUE THREAD

**Issue by cosmicgelatin** [samedifferent/Ecologics#46]
### Mod Version

1.6.3

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

Even if the config is set to not replace Azalea trees, Azalea trees grown from Azalea Flowers will use Ecologics's Azalea Log instead of the vanilla Oak Log.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8608925/latest.log)

**Comment by samedifferent** [comment]
This is not a bug. This is intended behavior. If you read the description for that config setting, it says that it only affects the _vanilla_ azalea trees. The point of the azalea flower is to allow the player to obtain the ecologics azalea wood even if other mods like Quark that add azalea are installed.
