### ISSUE TITLE
[Bug]: Running the mod on a clean world gives me a wall of text of errors

### ISSUE THREAD

**Issue by ccrowles** [samedifferent/Ecologics#48]
### Mod Version

1.6.3

### Mod Loader

Forge

### Mod Loader Version

40.1.16

### What happened?

Running Ecologics on a clean instance (new world, only ecologics and geckolib, no resourcepacks, no shaderpacks, nothing) on Minecraft 1.18.2 gives me a wall of text of errors.
![image](https://user-images.githubusercontent.com/12866474/167247993-b8d33a52-498e-4b2e-867a-878fffb8def9.png)
It's too big to even screenshot it all, but I've provided the logfile and the PolyMC launcher output below.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8644803/latest.log)

And [this](https://0x0.st/om-c.txt) is the output I got from PolyMC.

**Comment by brdle** [comment]
All recipe errors should be fixed with #52
As for loot_table errors, those are covered by #39 and therefore this is a duplicate

**Comment by samedifferent** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3790802
