### ISSUE TITLE
[Bug]: infinite coconut / minor incomatibility with carry on

### ISSUE THREAD

**Issue by kuba26038** [samedifferent/Ecologics#53]
### Mod Version

ecologics-FORGE-1.18.2-1.6.3

### Mod Loader

Forge

### Mod Loader Version

40.1.19

### What happened?

whenever i pick up a coconut crab that lost his shell, he regrows his shell and when i place him down it breaks again, allowing infinite coconu

https://user-images.githubusercontent.com/81324988/168413150-f9fd016c-32ad-4046-941c-c18eba6256bf.mp4

t

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8692350/latest.log)

**Comment by samedifferent** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3804127
