### ISSUE TITLE
[Bug]: Trying to add redstone to any potion results in 8 minute potion of sliding

### ISSUE THREAD

**Issue by BIG-Viljo** [samedifferent/Ecologics#55]
### Mod Version

1.6.6

### Mod Loader

Forge

### Mod Loader Version

41.1.23

### What happened?

Putting redstone into the item input slot and then inserting any potions (even base ones) in the bottom row, turns them into 8 minute potion of sliding. I had the same issue with mod called "Earth Mobs" (link to the report: (https://github.com/baguchan/EarthMobs/issues/7)). They "fixed" it by removing the ability to brew the potion altogether. This has been tested with only Ecologics and GecoLib installed.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8754626/latest.log)

**Comment by samedifferent** [comment]
I am having trouble reproducing this issue. Which potion specifically is this issue occuring with?

**Comment by samedifferent** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3804127
