### ISSUE TITLE
[Bug]: Thin ice grid/lattice-like appearance

### ISSUE THREAD

**Issue by Helpbot3000** [samedifferent/Ecologics#56]
### Mod Version

1.6.6

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.2-40.1.20

### What happened?

When thin ice blocks are placed next to each other, the faces that are touching are still visible, unlike with regular ice and glass blocks.

https://imgur.com/a/giFUscP

I reported this before, but because I did not include an image the exact problem was not clear.

### latest.log

I do not believe this is necessary for this bug, but if it is I will provide one.

**Comment by samedifferent** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3804127
