### ISSUE TITLE
[Bug]: Game crashes right before loading

### ISSUE THREAD

**Issue by JKaiya** [samedifferent/Ecologics#63]
### Mod Version

1.19-2.0.1

### Mod Loader

Forge

### Mod Loader Version

1.19

### What happened?

Gane crasges right before loading. Noticed this is also a problem with the Biomes O Plenty mod. Someone on there replied that it has to possibly be due to the forge version.

### latest.log

[crash-2022-06-16_21.25.26-client.txt](https://github.com/samedifferent/Ecologics/files/8924517/crash-2022-06-16_21.25.26-client.txt)

**Comment by samedifferent** [comment]
Ecologics is not mentioned anywhere in that crash log so I'm not sure why you assume the problem is with my mod. That log is also incomplete. Send the full latest.log file, which can be found in your logs folder.

**Comment by samedifferent** [comment]
I just checked the official forge discord server, and yes this appears to be a bug with the forge version. Forge changed some code between versions and it broke preexisting worlds. This is completely out of my control and has nothing to do with Ecologics. Also, forge 1.19 is still in beta, as you can see by the warning message that appears at the top of the title screen. Don't expect everything to be stable, and always backup your worlds before updating to the newest forge versions.

**Comment by JKaiya** [comment]
> I just checked the official forge discord server, and yes this appears to be a bug with the forge version. Forge changed some code between versions and it broke preexisting worlds. This is completely out of my control and has nothing to do with Ecologics. Also, forge 1.19 is still in beta, as you can see by the warning message that appears at the top of the title screen. Don't expect everything to be stable, and always backup your worlds before updating to the newest forge versions.

I think this is fixable as Biomes O Plenty just updated/released a new version which works. I am not a coder though so I have no idea where to point at the issue / help
