### ISSUE TITLE
[Mod Compatibilty] Ecologics crashes when used with SnowyLeavesPlus

### ISSUE THREAD

**Issue by theRookieCoder** [samedifferent/Ecologics#64]
## Mod Version

2.0.1

## Mod Loader

Fabric

## Mod Loader Version

0.14.8

## What happened?

Hi! I'm the developer of [SnowyLeavesPlus](https://github.com/theRookieCoder/SnowyLeavesPlus), and a user recently discovered a mod incompatibility with my mod and Ecologics (theRookieCoder/SnowyLeavesPlus#5). My mod is pretty simple, it adds a block state to `LeavesBlocks` using mixins (in [this file](https://github.com/theRookieCoder/SnowyLeavesPlus/blob/master/src/main/java/io/github/therookiecoder/snowyleavesplus/mixin/LeavesBlockMixin.java)). TBH I'm a rather _rookie_ modder, and I don't really understand what could be causing this, all I could figure it is that there's an issue with my mixins and your block registering. I would really appreciate it if you could help me out on this, and I hope we can work together to solve this.

## Crash Report

[crash-report.txt](https://github.com/samedifferent/Ecologics/files/8940633/crash-2022-06-20_17.57.35-client.txt)

**Comment by samedifferent** [comment]
I submitted a PR that fixes this issue, and should prevent future issues with other mods' custom leaves.
