### ISSUE TITLE
Crashes Immediately 

### ISSUE THREAD

**Issue by DinoFighter** [samedifferent/Ecologics#66]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

41.0.45

### What happened?

Immediately Crashes when I press play, with no other mods installed. 1.19

### latest.log

[crash-2022-06-21_16.26.02-client.txt](https://github.com/samedifferent/Ecologics/files/8952602/crash-2022-06-21_16.26.02-client.txt)

**Comment by samedifferent** [comment]
I'm looking at the crash report and it doesn't even seem like you have Ecologics installed.

**Comment by DinoFighter** [comment]
I might have clicked the wrong file.

**Comment by DinoFighter** [comment]
[crash-2022-06-21_16.47.57-client.txt](https://github.com/samedifferent/Ecologics/files/8952725/crash-2022-06-21_16.47.57-client.txt)

**Comment by DinoFighter** [comment]
The mod should be there in this one, and if its not then I don't know what's wrong.

**Comment by samedifferent** [comment]
That log doesn't mention it either. Do you have the correct version of GeckoLib installed too?

**Comment by DinoFighter** [comment]
I have the 1.19 forge version of GeckoLib

**Comment by PhoenixVX** [comment]
Can you display both your instance/profile's home directory, and your mods folder?

**Comment by DinoFighter** [comment]
What is profile's home directory? Also when I copy the mods github says it doesnt support file type.

**Comment by PhoenixVX** [comment]
In the vanilla Minecraft Launcher, you can click installations at the top, Click on the instance's three dots that pop up on hover, press edit, and see what Game Directory says. As for the mods folder, send an image of where it's at and what's in it.

**Comment by DinoFighter** [comment]
The directory says its in the Minecraft folder, if thats what you mean.

**Comment by DinoFighter** [comment]
The mods folder is in the Minecraft folder and it has ecologics-forge-1.19-2.0.1 and geckolib-quilt-1.19-3.1.0

**Comment by DinoFighter** [comment]
I'm sorry if I'm not understanding.

**Comment by samedifferent** [comment]
The issue is that you are using the **_Quilt_** version of geckolib, not **_Forge_**. Here is the link to the proper forge version: https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3827261

**Comment by DinoFighter** [comment]
It works now, thank you both for your help.
