### ISSUE TITLE
[Bug]: TPS Pinguin

### ISSUE THREAD

**Issue by TheButterbrotMan** [samedifferent/Ecologics#67]
### Mod Version

ecologics-FABRIC-1.18.2-1.5.4

### Mod Loader

Fabric

### Mod Loader Version

0.14.7

### What happened?

Im experiencing a low tps in my modpack. It seems like it is caused by the penguins.

### latest.log

https://spark.lucko.me/TLY51OmMDO

**Comment by samedifferent** [comment]
Looking at the log, there is no mention of penguins. Can you explain how you came to the conclusion that the penguins are causing this?

**Comment by TheButterbrotMan** [comment]
It's at top![Screenshot_2022-06-24-02-08-05-077_com.discord.jpg](https://user-images.githubusercontent.com/64548098/175435101-db34e8f6-8acd-4a21-aab5-56207e27d0a0.jpg)

**Comment by TheRanker** [comment]
Spark told us penguins is lagging the modpack. And it is... Badly.

**Comment by samedifferent** [comment]
Fixed, will be in next release
