### ISSUE TITLE
[Bug]: Incompatibility with Paradise Lost

### ISSUE THREAD

**Issue by lamoyrl90** [samedifferent/Ecologics#69]
### Mod Version

1.7.1

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### What happened?

Crash happens with only Paradise Lost 1.6.9 (nice) and Ecologics 1.7.1 installed on the instance. Game fails to launch. Much sadness had.

This wasn't occurring before 1.7.1, and it's referencing SheepEntity in the stacktrace, so I assume it has to do with the shears mixins.

### latest.log

https://pastebin.com/YctqMFCX

**Comment by samedifferent** [comment]
Fixed in https://github.com/samedifferent/Ecologics/commit/4e5f4b8dbb1494c7e7693b636b6b75b17cf8d510
Will be released on curseforge shortly!
