### ISSUE TITLE
[Bug]: Ecologics 1.7.1 mixins error prevents server launch

### ISSUE THREAD

**Issue by MoonMoonShark** [samedifferent/Ecologics#72]
### Mod Version

ecologics-forge-1.18.2-1.7.1

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.2-40.1.54

### What happened?

upgraded server to ecologics-forge-1.18.2-1.7.1 but get a crash during load.

**Error:** `Caused by: java.lang.IllegalArgumentException: The specified resource 'ecologics-common.mixins.json' was invalid or could not be read`

**Minecraft:** 1.18.2
**Forge:** forge-1.18.2-40.1.54
**Ecologics:** ecologics-forge-1.18.2-1.7.1
**Modpack:** https://www.curseforge.com/minecraft/modpacks/the-lighthouse/files/3859356

### latest.log

**Server Log:** (https://pastebin.com/h1s6FwEN)

there is no crash log, and Latest and Debug stop with no further text as soon as Ecologics loads.

**Comment by samedifferent** [comment]
Are you able to reproduce the issue with only ecologics and no other mods installed?

**Comment by MoonMoonShark** [comment]
well, whatever the problem was, it seems to have been rectified, through a combination of updating this and other mods. so, gg team. :D
