### ISSUE TITLE
[Bug]: Crash when joining server because ecologics:slippery is not registered

### ISSUE THREAD

**Issue by SuomiIkuisesti** [samedifferent/Ecologics#75]
### Mod Version

1.7.4

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### What happened?

I tried to join my server, which had the same modpack as mine. My game crashed.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/9135614/latest.log)

**Comment by samedifferent** [comment]
You need to use the latest forge version

**Comment by SuomiIkuisesti** [comment]
it's the latest forge for 1.18.2

**Comment by samedifferent** [comment]
Can you try with only Ecologics and no other mods installed?

**Comment by SuomiIkuisesti** [comment]
it works alone

**Comment by SuomiIkuisesti** [comment]
i tried it with my original modpack, this time it said it required geckolib, but after i installed geckolib it gave a whole new problem this time
