### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aikirob** [samedifferent/Ecologics#79]
### Mod Version

2.1.4

### Mod Loader

Fabric

### Mod Loader Version

1.19

### What happened?

coconut tree leaves are grey instead of green when used with better leaves resource pack, dont know why this is an issue, the color shouldnt change but it does...

### latest.log

wasnt a crash, doesnt need a loh

**Comment by samedifferent** [comment]
Report this issue to the resource pack.
