### ISSUE TITLE
[Bug]:crashes instantly

### ISSUE THREAD

**Issue by codeseven7** [samedifferent/Ecologics#82]
### Mod Version

2.1.6

### Mod Loader

Fabric

### Mod Loader Version

fabric loader 0.14.9

### What happened?

I wanted to make a modded survival and when i installed the ecologics mod it crashed for no reason.. it was working without it too
![image](https://user-images.githubusercontent.com/111052077/184107329-7c8e313f-3fb1-4117-afd4-a4a2b36c62cc.png)

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/9307725/latest.log)

**Comment by samedifferent** [comment]
This is because I have not updated the mod to 1.19.2 yet. I will do so shortly
