### ISSUE TITLE
[Request}: A way to make thin ice turn to water when broken in mc 1.19

### ISSUE THREAD

**Issue by Imcaam** [samedifferent/Ecologics#83]
### Mod Version

2.17/2.18

### Mod Loader

Fabric

### Mod Loader Version

-

### What happened?

Hi, first thing I love your mod, but I've been using mc 1.19 and the newest update got a feature that I would really like in my SP. Is there a way to make it happen? thanks

### latest.log

-

**Comment by samedifferent** [comment]
Sorry, but I will not be updating 1.19 any longer. That would mean I would need to maintain 6 different versions of the mod (Forge and fabric for 1.18.2, 1.19, and 1.19.1/2). Please use 1.19.1/2, as pretty much all 1.19 mods work with it so it shouldn't be a big deal to update your existing worlds.
