### ISSUE TITLE
[Bug]: Ecologics fabric-1.19.2-2.1.8.1 crash on startup

### ISSUE THREAD

**Issue by lospejos** [samedifferent/Ecologics#87]
### Mod Version

1.19.2-2.1.8.1

### Mod Loader

Fabric

### Mod Loader Version

fabric-api-0.59.0+1.19.2

### What happened?

1) Have created Minecraft instance with mods:
`fabric-api-0.59.0+1.19.2`
`modmenu-4.0.6`
`ecologics-fabric-1.19.2-2.1.8.1`

2) Started this instance
3) Crash occurred: InvalidAccessorException: No candidates were found matching <init>(ILnet/minecraft/class_3414;Lnet/minecraft/class_1792$class_1793;)V in net/minecraft/class_1813 for ecologics.mixins.json:RecordItemAccessor from mod ecologics->@Invoker[OBJECT_FACTORY]::invokeConstructor(ILnet/minecraft/class_3414;Lnet/minecraft/class_1792$class_1793;)Lnet/minecraft/class_1813; [INJECT Applicator Phase -> ecologics.mixins.json:RecordItemAccessor from mod ecologics -> Apply Accessors ->  -> Locate -> ecologics.mixins.json:RecordItemAccessor from mod ecologics->@Invoker[OBJECT_FACTORY]::invokeConstructor(ILnet/minecraft/class_3414;Lnet/minecraft/class_1792$class_1793;)Lnet/minecraft/class_1813;]

### latest.log

https://gist.github.com/lospejos/edee6da841043c8cbb6e0ca69735d4d9

**Comment by samedifferent** [comment]
You are using the wrong version of Ecologics. You need to use the 1.19.2 version, not the 1.19 version.
