### ISSUE TITLE
[Bug]: Little issues

### ISSUE THREAD

**Issue by jerkery678** [samedifferent/Ecologics#91]
### Mod Version

2.1.10

### Mod Loader

Forge

### Mod Loader Version

43.1.1

### What happened?

https://imgur.com/a/vy4f00h

1. Sandcastle z-fighting
2. Weird pot sound name

Not major issues though, but might affect your mental health a little bit.

### latest.log

null

**Comment by samedifferent** [comment]
The issue is being attributed to the mod Faster Entity Animations. Please report it to them.
