### ISSUE TITLE
[Bug]: Hanging Coconut crashes the game (on my head)

### ISSUE THREAD

**Issue by Nekkok** [samedifferent/Ecologics#92]
### Mod Version

Ecologics 2.1.10

### Mod Loader

Fabric

### Mod Loader Version

Fabric 0.63.0

### What happened?

Sometimes, the game crashes due to a "coconut problem". I think it is better described in the log.
Thank you n_n

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/9815364/latest.log)

**Comment by Nekkok** [comment]
In the same line, as I started a new world:
[latest.log](https://github.com/samedifferent/Ecologics/files/9815654/latest.log)

**Comment by samedifferent** [comment]
The issue is being attributed to the mod Faster Entity Animations. Please report it to them.
