### ISSUE TITLE
[Bug]: incompatability crash

### ISSUE THREAD

**Issue by simplyskellix** [samedifferent/Ecologics#93]
### Mod Version

1.19.2-2.1.10

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### What happened?

(mod conflict)  whenevery i break a block the game crashes, i have tried this a number of ways but the crash only happens with ecologics installed along with immersive weathering. upon crash the launcher states there is something going on with Azalea related blocks.

### latest.log

[crash-2022-10-19_21.36.18-client.txt](https://github.com/samedifferent/Ecologics/files/9825259/crash-2022-10-19_21.36.18-client.txt)

**Comment by samedifferent** [comment]
This seems to be an issue with how immersive weathering is registering their bark items. Please report this issue to their github.
