### ISSUE TITLE
[Bug]: Crashed after playing for a few minutes

### ISSUE THREAD

**Issue by Samapoke** [samedifferent/Ecologics#94]
### Mod Version

2.1.10

### Mod Loader

Forge

### Mod Loader Version

43.1.43

### What happened?

I created a new world and started playing, but after a while it's getting freezed and crash.

### latest.log

https://gist.github.com/Samapoke/b1e343ec437c2e61bea5a7838f949048 (latest.log)
https://gist.github.com/Samapoke/1c114fe11f91166529693bc6db05c351 (crash-2022-10-20_11.35.27-client.txt)

**Comment by samedifferent** [comment]
This was a big with the Supplementaries mod, but they fixed it. Update your Supplementaries version.

**Comment by Samapoke** [comment]
> Supplementaries

I don't even use that mod...

**Comment by samedifferent** [comment]
Sorry, I meant Immersive Weathering. They're made by the same developer.

**Comment by Samapoke** [comment]
Ok, thank you a lot!
