### ISSUE TITLE
[Bug]: Azalea Tree still generating even when turned off

### ISSUE THREAD

**Issue by LeonKappaX** [samedifferent/Ecologics#95]
### Mod Version

2.1.10

### Mod Loader

Forge

### Mod Loader Version

43.1.43

### What happened?

Turned off the Ecologics Azalea Tree from spawning because I don't want a second pink treeand wanted to use the one from Quark instead.
Using Bone Meal on Azalea Bushes works just fine and gives me the green Quark Azalea Logs,
however, the Azalea Trees that spawn in the wild still use the pink Logs from Ecologics.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/9895992/latest.log)

**Comment by samedifferent** [comment]
This is not a bug. In 1.19, Forge changed their biome modifier system. Now, world generation must be configured by making a datapack. See this tutorial: https://github.com/samedifferent/Ecologics/wiki/Ecologics-Configuration-(Forge)
