### ISSUE TITLE
[Bug]: Crash for some reason when seeing penguin in the newest version 

### ISSUE THREAD

**Issue by Kasax007** [samedifferent/Ecologics#96]
### Mod Version

Ecologics 2.1.10 (Fabric 1.19.2)

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### What happened?

I created a world and immediately crashed due to seeing a penguin if I believe what the log file is saying. I also have different mods installed. You can find the mod list under Dreamcraft Fabric for 1.19.2.

### latest.log

https://pastebin.com/DTgf8mT9

**Comment by samedifferent** [comment]
The issue is being attributed to the mod Faster Entity Animations. Please report it to them.
